# Using paramiko to connect to your sftp server and rename a bunch of copies of same file in a lot of folders.
# the list of urls was collected through general search for the file in filezilla sftp client

import paramiko
def file_exists(sftp, path):
    """
    Check if a file exists on the remote SFTP server.
    """
    try:
        sftp.stat(path)
        return True
    except FileNotFoundError:
        return False
    
def rename_htaccess_on_sftp(server, username, password, directory):
    with paramiko.Transport((server, 22)) as transport:
        transport.connect(username=username, password=password)
        sftp = paramiko.SFTPClient.from_transport(transport)
        
        htaccess_path = f"{directory}/.htaccess"
        new_htaccess_path = f"{directory}/old.bak"
        
        if file_exists(sftp, htaccess_path):
            sftp.rename(htaccess_path, new_htaccess_path)
            print(f"Renamed .htaccess in {directory}")
        else:
            print(f".htaccess not found in {directory}")

# SFTP server details
server = "your.sftp.server.address"
username = "your_user_id"
password = "your_sftp_password"  # Note: It's better to use key-based authentication instead of password

# List of directories
directories = [
"/lamp0/web/vhosts/example.com/htdocs/.tmb.backup/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/blue/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/coffee/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/ectoplasm/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/light/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/midnight/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/modern/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/ocean/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/css/colors/sunrise/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/images/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/includes/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/js/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/js/widgets/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/maint/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/network/",
"lamp0/web/vhosts/example.com/htdocs/wp-admin/user/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/cloudflare/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/cloudfront/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/envhttps/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/loadbalancer/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/serverhttps1/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/serverhttpson/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/serverhttpxforwardedssl1/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/serverhttpxforwardedsslon/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/serverhttpxproto/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/plugins/really-simple-ssl/testssl/serverport443/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/test-upgrade/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/themes/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2018/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2018/11/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2020/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2020/01/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2020/02/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2021/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2021/02/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/03/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/04/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/05/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/06/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/07/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/2023/08/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/astra-sites/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/elementor/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/elementor/css/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/elementor/thumbs/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/maxmegamenu/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/wpforms/",
"lamp0/web/vhosts/example.com/htdocs/wp-content/uploads/wpforms/cache/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/ID3/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/IXR/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/PHPMailer/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/library/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Auth/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Cookie/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Exception/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Exception/Http/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Exception/Transport/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Proxy/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Response/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Transport/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Requests/src/Utility/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Cache/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Content/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Content/Type/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Decode/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Decode/HTML/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/HTTP/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Net/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/Parse/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/XML/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/SimplePie/XML/Declaration/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Text/Diff/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Text/Diff/Engine/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/Text/Diff/Renderer/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/assets/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/block-patterns/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/block-supports/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/archives/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/audio/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/avatar/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/block/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/button/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/buttons/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/calendar/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/categories/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/code/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/column/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/columns/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comment-author-name/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comment-content/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comment-date/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comment-edit-link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comment-reply-link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comment-template/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comments/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comments-pagination/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comments-pagination-next/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comments-pagination-numbers/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comments-pagination-previous/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/comments-title/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/cover/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/embed/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/file/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/freeform/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/gallery/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/group/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/heading/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/home-link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/html/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/image/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/latest-comments/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/latest-posts/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/legacy-widget/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/list/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/list-item/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/loginout/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/media-text/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/missing/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/more/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/navigation/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/navigation-link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/navigation-submenu/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/nextpage/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/page-list/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/page-list-item/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/paragraph/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/pattern/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-author/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-author-biography/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-author-name/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-comments-form/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-content/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-date/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-excerpt/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-featured-image/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-navigation-link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-template/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-terms/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/post-title/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/preformatted/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/pullquote/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query-no-results/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query-pagination/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query-pagination-next/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query-pagination-numbers/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query-pagination-previous/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/query-title/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/quote/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/read-more/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/rss/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/search/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/separator/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/shortcode/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/site-logo/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/site-tagline/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/site-title/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/social-link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/social-links/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/spacer/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/table/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/tag-cloud/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/template-part/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/term-description/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/text-columns/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/verse/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/video/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/blocks/widget-group/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/certificates/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/block-directory/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/block-editor/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/block-library/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/components/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/customize-widgets/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/edit-post/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/edit-site/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/edit-widgets/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/editor/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/format-library/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/list-reusable-blocks/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/nux/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/reusable-blocks/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/css/dist/widgets/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/customize/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/fonts/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/html-api/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/images/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/images/crystal/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/images/media/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/images/smilies/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/codemirror/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/crop/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/dist/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/dist/development/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/dist/vendor/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/imgareaselect/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/jcrop/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/jquery/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/jquery/ui/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/mediaelement/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/mediaelement/renderers/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/plupload/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/swfupload/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/thickbox/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/langs/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/charmap/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/colorpicker/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/compat3x/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/compat3x/css/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/directionality/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/fullscreen/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/hr/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/image/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/link/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/lists/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/media/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/paste/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/tabfocus/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/textcolor/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wordpress/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wpautoresize/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wpdialogs/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wpeditimage/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wpemoji/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wpgallery/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wplink/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wptextpattern/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/plugins/wpview/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/skins/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/skins/lightgray/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/skins/lightgray/fonts/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/skins/lightgray/img/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/skins/wordpress/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/skins/wordpress/images/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/themes/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/themes/inlite/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/themes/modern/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/js/tinymce/utils/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/php-compat/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/pomo/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/rest-api/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/rest-api/endpoints/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/rest-api/fields/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/rest-api/search/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sitemaps/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sitemaps/providers/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/lib/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/namespaced/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/namespaced/Core/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/namespaced/Core/ChaCha20/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/namespaced/Core/Curve25519/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/namespaced/Core/Poly1305/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/Base64/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/ChaCha20/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/Curve25519/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/Curve25519/Ge/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/Poly1305/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core/SecretStream/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core32/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core32/ChaCha20/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core32/Curve25519/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core32/Curve25519/Ge/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core32/Poly1305/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/Core32/SecretStream/",
"lamp0/web/vhosts/example.com/htdocs/wp-includes/sodium_compat/src/PHP52/"
    # ... add all directories to this list
]

# Rename .htaccess in each directory
for directory in directories:
    rename_htaccess_on_sftp(server, username, password, directory)
